#!/bin/sh

set -eu

secret() {
    openssl rand -hex "$1"
}

export COMPOSE_PROJECT_NAME="campement-smoke-local-$$"
APP_SECRET=$(secret 32)
POSTGRES_PASSWORD=$(secret 24)
POSTGRES_APP_PASSWORD=$(secret 24)
POSTGRES_MIGRATOR_PASSWORD=$(secret 24)
POSTGRES_BACKUP_PASSWORD=$(secret 24)
POSTGRES_HEALTHCHECK_PASSWORD=$(secret 24)
export APP_SECRET POSTGRES_PASSWORD POSTGRES_APP_PASSWORD
export POSTGRES_MIGRATOR_PASSWORD POSTGRES_BACKUP_PASSWORD
export POSTGRES_HEALTHCHECK_PASSWORD
export NGINX_HOST_PORT="${NGINX_HOST_PORT:-18083}"
export POSTGRES_HOST_PORT="${POSTGRES_HOST_PORT:-15437}"

exec ./scripts/ci-production-smoke.sh
